GET http://localhost:3000/reservas

###

GET http://localhost:3000/reservas/2

###

POST http://localhost:3000/reservas HTTP/1.1
Content-Type: application/json

{
        "Id_reserva": "1 ",
        "estado" : "activa"
}

###
PUT http://localhost:3000/reservas/2 HTTP/1.1
Content-Type: application/json

{
    "estado": "inactiva"
}
###
DELETE http://localhost:3000/reservas/4 HTTP/1.1


